ci: 自动部署

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,8 +10,47 @@ permissions:
   contents: write
 
 jobs:
-  build:
-    name: Build Docusaurus
+  deloy-git:
+    name: Delaoy to Github Pages
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 18
+          cache: yarn
+
+      - name: edit baseUrl
+        run: |
+          sed -i 's|baseUrl: '\''/\''|baseUrl: '\''/fly-docs-next/\''|' docusaurus.config.js
+
+      - name: Install dependencies
+        run: yarn install --frozen-lockfile
+      - name: Build website
+        run: yarn build
+
+      - name: Revert baseUrl
+        run: |
+          sed -i 's|baseUrl: '\''/fly-docs-next/\''|baseUrl: '\''/\''|' docusaurus.config.js
+
+      - name: Check for index.html
+        run: |
+          if [ ! -f build/index.html ]; then
+            echo "index.html not found in build directory"
+            exit 1
+          fi
+          echo "index.html found in build directory"
+
+      - name: Delaoy to Github Pages
+        uses: JamesIves/github-pages-deploy-action@v4
+        with:
+          branch: gh-pages
+          folder: build
+
+  deloy-cf:
+    name: Delaoy to Cloudflare Pages
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -35,16 +74,10 @@ jobs:
           fi
           echo "index.html found in build directory"
 
-      - name: Delaoy to Github Pages
-        uses: JamesIves/github-pages-deploy-action@v4
-        with:
-          branch: gh-pages
-          folder: build
-
       - name: Delaoy to Cloudflare Pages
         env:
           CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
         run: |
           npm install wrangler --save-dev
-          npx wrangler pages deploy build --project-name=fly-docs --branch production
+          npx wrangler pages deploy build --project-name=fly-docs --commit-dirty=true --branch=main
